CREATE SEQUENCE Estado_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE; 
CREATE TABLE Estado (
  EstadoID NUMBER DEFAULT  Estado_seq.NEXTVAL PRIMARY KEY NOT NULL,
  UF VARCHAR2(2) NOT NULL,
  Nome VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE Cidade_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Cidade (
  CidadeID NUMBER DEFAULT  Cidade_seq.NEXTVAL PRIMARY KEY NOT NULL,
  Nome VARCHAR2(255) NOT NULL,
  EstadoID NUMBER,
  CONSTRAINT fk_ciade_estadoID FOREIGN KEY (EstadoID) REFERENCES Estado(EstadoID)
);

CREATE SEQUENCE UsuarioRoles_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE UsuarioRoles(
  UsuarioRoleID NUMBER DEFAULT  UsuarioRoles_seq.NEXTVAL PRIMARY KEY NOT NULL,
  Descricao VARCHAR2(255) NOT NULL,
  Identificador VARCHAR(50) NOT NULL
);

CREATE SEQUENCE Usuario_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Usuario (
  UsuarioID NUMBER DEFAULT  Usuario_seq.NEXTVAL PRIMARY KEY NOT NULL,
  Nome VARCHAR2(100) NOT NULL,
  Senha VARCHAR2(1000) NOT NULL,
  CidadeID NUMBER NOT NULL,
  Endereco VARCHAR2(300) NOT NULL,
  UsuarioRoleID NUMBER DEFAULT 0,
  CONSTRAINT fk_usuario_cidadeID FOREIGN KEY (CidadeID) REFERENCES Cidade(CidadeID),
  CONSTRAINT fk_usuario_usuarioRoleID FOREIGN KEY (usuarioRoleID) REFERENCES usuarioRoles(usuarioRoleID)
);

CREATE SEQUENCE Venda_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Venda (
  VendaID NUMBER DEFAULT  Venda_seq.NEXTVAL PRIMARY KEY NOT NULL,
  ValorTotalVenda NUMBER(5,2) NOT NULL,
  UsuarioID NUMBER NOT NULL,
  CONSTRAINT fk_venda_usuarioID FOREIGN KEY (usuarioID) REFERENCES Usuario(usuarioID)
);

CREATE SEQUENCE Receita_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Receita (
  ReceitaID NUMBER DEFAULT Receita_seq.NEXTVAL PRIMARY KEY NOT NULL,
  ValorVenda NUMBER(10,2) NOT NULL,
  Nome VARCHAR2(255) NOT NULL
);
CREATE SEQUENCE Pedido_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Pedido (
  PedidoID NUMBER DEFAULT Pedido_seq.NEXTVAL PRIMARY KEY NOT NULL,
  ValorVenda NUMBER(5,2) NOT NULL,
  VendaID NUMBER NOT NULL,
  ReceitaID NUMBER NOT NULL,
  Quantidade NUMBER NOT NULL,
  CONSTRAINT fk_pedido_vendaID FOREIGN KEY (VendaID) REFERENCES Venda(VendaID),
  CONSTRAINT fk_pedido_receitaID FOREIGN KEY (ReceitaID) REFERENCES Receita(ReceitaID)
);

CREATE SEQUENCE Ingrediente_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Ingrediente (
  IngredienteID NUMBER DEFAULT Ingrediente_seq.NEXTVAL PRIMARY KEY NOT NULL,
  Nome VARCHAR2(255) NOT NULL,
  Alergenico NUMBER(1) DEFAULT 0,
  UnidadeID NUMBER NOT NULL,
  CONSTRAINT fk_ingrediente_unidadeID FOREIGN KEY (UnidadeID) REFERENCES Unidade(UnidadeID)
);

CREATE SEQUENCE ReceitaIngrediente_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE ReceitaIngredientes(
  ReceitaIngredienteID NUMBER DEFAULT ReceitaIngrediente_seq.NEXTVAL PRIMARY KEY NOT NULL,
  ReceitaID NUMBER NOT NULL,
  IngredienteID NUMBER NOT NULL,
  QuantidadeUsada NUMBER(10,2),
  CONSTRAINT fk_receitaIngredientes_receitaID FOREIGN KEY (ReceitaID) REFERENCES Receita(ReceitaID),
  CONSTRAINT fk_receitIngredientes_ingredienteID FOREIGN KEY (IngredienteID) REFERENCES Ingrediente(IngredienteID)
);

CREATE SEQUENCE Lote_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Lote(
  LoteID NUMBER DEFAULT Lote_seq.NEXTVAL PRIMARY KEY NOT NULL,
  ReceitaID NUMBER NOT NULL,
  DataProducao DATE NOT NULL,
  DataValidade DATE NOT NULL,
  ValorProducao NUMBER(7,2),
  CadastroLoteEstoqueConcluido NUMBER(1) DEFAULT 0,
  QuantidadeProduzida NUMBER NOT NULL,
  QuantidadeRestante NUMBER NOT NULL,
  CONSTRAINT fk_lote_receitaID FOREIGN KEY (ReceitaID) REFERENCES Receita(ReceitaID)
);

CREATE SEQUENCE Unidade_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Unidade (
  UnidadeID NUMBER DEFAULT Unidade_seq.NEXTVAL PRIMARY KEY NOT NULL,
  Descricao VARCHAR2(255),
  Identificador VARCHAR2(50)
);

CREATE SEQUENCE Estoque_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE Estoque(
  EstoqueID NUMBER DEFAULT Estoque_seq.NEXTVAL PRIMARY KEY NOT NULL,
  IngredienteID NUMBER NOT NULL,
  QuantidadeComprada NUMBER(10,2) NOT NULL,
  QuantidadeRestante NUMBER(10,2) NOT NULL,
  DataValidade DATE NOT NULL,
  ValorCompra NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_estoque_ingredienteID FOREIGN KEY (IngredienteID) REFERENCES Ingrediente(IngredienteID)
);

CREATE SEQUENCE CustosGerais_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE CustosGerais(
  CustoGeralID NUMBER DEFAULT CustosGerais_seq.NEXTVAL PRIMARY KEY NOT NULL,
  Descricao VARCHAR2(500) NOT NULL,
  valorPorcentagem NUMBER(10,2) NOT NULL,
  Identificador VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE LoteEstoque_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE LoteEstoque(
  LoteEstoqueID NUMBER DEFAULT LoteEstoque_seq.NEXTVAL PRIMARY KEY NOT NULL,
  LoteID NUMBER NOT NULL,
  EstoqueID NUMBER NOT NULL,
  QuantidadeUsada NUMBER(15,2) DEFAULT 0,
  CONSTRAINT fk_LoteEstoque_estoqueID FOREIGN KEY (LoteID) REFERENCES Lote(LoteID),
  CONSTRAINT fk_LoteEstoque_loteID FOREIGN KEY (EstoqueID) REFERENCES Estoque(EstoqueID)
);


DROP TABLE Lote
Drop Table Estoque
DROP TABLE LOTEESTOQUE
DROP TABLE UNIDADE
DROP TABLE Receita
DROP TABLE INGREDIENTE
